name: pytorch-brats
channels:
  - defaults
  - conda-forge
  - nvidia
  - pytorch
dependencies:
  - annotated-types=0.6.0=py39haa95532_1
  - appdirs=1.4.4=pyhd3eb1b0_0
  - asttokens=3.0.0=pyhd8ed1ab_1
  - blas=1.0=mkl
  - brotli=1.2.0=h2d644bc_1
  - brotli-bin=1.2.0=hfd05255_1
  - brotlicffi=1.0.9.2=py39h885b0b7_2
  - bzip2=1.0.8=h2bbff1b_6
  - ca-certificates=2025.12.2=haa95532_0
  - certifi=2025.10.5=py39haa95532_0
  - cffi=2.0.0=py39h02ab6af_0
  - charset-normalizer=3.4.4=py39haa95532_0
  - click=8.1.8=py39haa95532_0
  - colorama=0.4.6=pyhd8ed1ab_1
  - comm=0.2.3=pyhe01879c_0
  - contourpy=1.3.0=py39h2b77a98_2
  - cpython=3.9.23=py39hd8ed1ab_0
  - cuda-cccl=12.9.27=0
  - cuda-cccl_win-64=12.9.27=0
  - cuda-cudart=12.1.105=0
  - cuda-cudart-dev=12.1.105=0
  - cuda-cupti=12.1.105=0
  - cuda-libraries=12.1.0=0
  - cuda-libraries-dev=12.1.0=0
  - cuda-nvrtc=12.1.105=0
  - cuda-nvrtc-dev=12.1.105=0
  - cuda-nvtx=12.1.105=0
  - cuda-opencl=12.9.19=0
  - cuda-opencl-dev=12.9.19=0
  - cuda-profiler-api=12.9.79=0
  - cuda-runtime=12.1.0=0
  - cuda-version=12.9=h9deaac8_3
  - cudnn=9.14.0.64=hef0acbb_0
  - cycler=0.12.1=pyhd8ed1ab_1
  - debugpy=1.8.16=py39h1f3cc84_0
  - decorator=5.2.1=pyhd8ed1ab_0
  - docker-pycreds=0.4.0=pyhd3eb1b0_0
  - eval_type_backport=0.2.2=pyha770c72_0
  - exceptiongroup=1.3.0=pyhd8ed1ab_0
  - executing=2.2.0=pyhd8ed1ab_0
  - expat=2.7.3=h885b0b7_4
  - filelock=3.17.0=py39haa95532_0
  - fonttools=4.59.1=py39h5769e4c_0
  - freetype=2.13.3=h0620614_0
  - giflib=5.2.2=h7edc060_0
  - gitdb=4.0.12=py39haa95532_0
  - gitpython=3.1.45=py39haa95532_0
  - gmp=6.3.0=h537511b_0
  - gmpy2=2.2.1=py39h827c3e9_0
  - icu=73.2=h63175ca_0
  - idna=3.11=py39haa95532_0
  - importlib-metadata=8.7.0=pyhe01879c_1
  - importlib-resources=6.5.2=pyhd8ed1ab_0
  - importlib_resources=6.5.2=pyhd8ed1ab_0
  - intel-openmp=2023.1.0=h59b6b97_46320
  - ipykernel=6.30.1=pyh3521513_0
  - ipython=8.18.1=pyh7428d3b_3
  - jedi=0.19.2=pyhd8ed1ab_1
  - jinja2=3.1.6=py39haa95532_0
  - joblib=1.5.1=pyhd8ed1ab_0
  - jpeg=9f=ha349fce_0
  - jupyter_client=8.6.3=pyhd8ed1ab_1
  - jupyter_core=5.8.1=pyh5737063_0
  - khronos-opencl-icd-loader=2025.07.22=h79b28c9_0
  - kiwisolver=1.4.7=py39h2b77a98_0
  - krb5=1.21.3=hdf4eb48_0
  - lcms2=2.16=hb4a4139_0
  - lerc=3.0=hd77b12b_0
  - libblas=3.9.0=1_h8933c1f_netlib
  - libbrotlicommon=1.2.0=hfd05255_1
  - libbrotlidec=1.2.0=hfd05255_1
  - libbrotlienc=1.2.0=hfd05255_1
  - libcblas=3.9.0=13_hc41557d_netlib
  - libclang13=21.1.7=default_ha2db4b5_3
  - libcublas=12.1.0.26=0
  - libcublas-dev=12.1.0.26=0
  - libcudnn=9.14.0.64=hef0acbb_0
  - libcudnn-dev=9.14.0.64=hef0acbb_0
  - libcufft=11.0.2.4=0
  - libcufft-dev=11.0.2.4=0
  - libcurand=10.3.10.19=0
  - libcurand-dev=10.3.10.19=0
  - libcusolver=11.4.4.55=0
  - libcusolver-dev=11.4.4.55=0
  - libcusparse=12.0.2.55=0
  - libcusparse-dev=12.0.2.55=0
  - libdeflate=1.17=h2bbff1b_1
  - libexpat=2.7.3=h885b0b7_4
  - libffi=3.4.4=hd77b12b_1
  - libjpeg-turbo=2.0.0=h196d8e1_0
  - libkrb5=1.21.3=h885b0b7_4
  - liblapack=3.9.0=13_h018ca30_netlib
  - libnpp=12.0.2.50=0
  - libnpp-dev=12.0.2.50=0
  - libnvjitlink=12.1.105=0
  - libnvjitlink-dev=12.1.105=0
  - libnvjpeg=12.1.1.14=0
  - libnvjpeg-dev=12.1.1.14=0
  - libpng=1.6.50=h46444df_0
  - libpq=17.6=h652a1e2_0
  - libsodium=1.0.20=hc70643c_0
  - libtiff=4.5.1=hd77b12b_0
  - libuv=1.48.0=h827c3e9_0
  - libwebp=1.3.2=hbc33d0d_0
  - libwebp-base=1.3.2=h3d04722_1
  - libzlib=1.3.1=h02ab6af_0
  - lightning-utilities=0.15.2=pyhd8ed1ab_0
  - lz4-c=1.9.4=h2bbff1b_1
  - m2w64-gcc-libgfortran=5.3.0=6
  - m2w64-gcc-libs=5.3.0=7
  - m2w64-gcc-libs-core=5.3.0=7
  - m2w64-gmp=6.1.0=2
  - m2w64-libwinpthread-git=5.0.0.4634.697f757=2
  - markupsafe=3.0.2=py39h827c3e9_0
  - matplotlib=3.9.1=py39hcbf5309_1
  - matplotlib-base=3.9.1=py39h5376392_2
  - matplotlib-inline=0.1.7=pyhd8ed1ab_1
  - mkl=2023.1.0=h6b88ed4_46358
  - mkl-service=2.4.0=py39h827c3e9_2
  - mkl_fft=1.3.11=py39h827c3e9_0
  - mkl_random=1.2.8=py39hc64d2fc_0
  - mpc=1.3.1=h827c3e9_0
  - mpfr=4.2.1=h56c3642_0
  - mpmath=1.3.0=py39haa95532_0
  - msys2-conda-epoch=20160418=1
  - munkres=1.1.4=pyhd8ed1ab_1
  - nest-asyncio=1.6.0=pyhd8ed1ab_1
  - networkx=3.2.1=py39haa95532_0
  - nibabel=5.3.2=pyha770c72_1
  - numpy=2.0.1=py39h055cbcc_1
  - numpy-base=2.0.1=py39h65a83cf_1
  - opencl-headers=2025.07.22=h885b0b7_0
  - openjpeg=2.5.2=hae555c5_0
  - openssl=3.6.0=h725018a_0
  - packaging=25.0=pyh29332c3_1
  - pandas=2.3.1=py39h743b7ac_0
  - parso=0.8.4=pyhd8ed1ab_1
  - patsy=1.0.1=pyhd8ed1ab_1
  - pickleshare=0.7.5=pyhd8ed1ab_1004
  - pillow=11.1.0=py39h096bfcc_0
  - pip=25.3=pyhc872135_0
  - platformdirs=4.3.8=pyhe01879c_0
  - prompt-toolkit=3.0.51=pyha770c72_0
  - protobuf=5.29.3=py39h5da7b33_0
  - psutil=7.0.0=py39ha55e580_0
  - pure_eval=0.2.3=pyhd8ed1ab_1
  - pycparser=2.23=py39haa95532_0
  - pydantic=2.12.2=py39haa95532_0
  - pydantic-core=2.41.4=py39h114bc41_0
  - pygments=2.19.2=pyhd8ed1ab_0
  - pyparsing=3.2.3=pyhe01879c_2
  - pyqt=5.15.4=py39h415ef7b_0
  - pyqt5-sip=12.9.0=py39h415ef7b_0
  - pysocks=1.7.1=py39haa95532_1
  - python=3.9.25=h716150d_1
  - python-dateutil=2.9.0.post0=pyhe01879c_2
  - python-tzdata=2025.2=pyhd8ed1ab_0
  - python_abi=3.9=2_cp39
  - pytorch=2.5.1=py3.9_cuda12.1_cudnn9_0
  - pytorch-cuda=12.1=hde6ce7c_6
  - pytorch-mutex=1.0=cuda
  - pytz=2025.2=pyhd8ed1ab_0
  - pywin32=311=py39h5fb4b08_0
  - pyyaml=6.0.2=py39h827c3e9_0
  - pyzmq=27.0.2=py39h248659b_0
  - qhull=2020.2=hc790b64_5
  - qt-main=5.15.2=h8b2cd8b_13
  - requests=2.32.5=py39haa95532_0
  - scikit-learn=1.6.1=py39hdd013cc_0
  - scipy=1.13.1=py39h1a10956_0
  - seaborn=0.13.2=hd8ed1ab_3
  - seaborn-base=0.13.2=pyhd8ed1ab_3
  - sentry-sdk=2.18.0=py39haa95532_0
  - setproctitle=1.3.6=py39h02ab6af_0
  - setuptools=80.9.0=py39haa95532_0
  - sip=6.5.1=py39h415ef7b_2
  - six=1.17.0=pyhe01879c_1
  - smmap=5.0.2=py39haa95532_0
  - sqlite=3.51.0=hda9a48d_0
  - stack_data=0.6.3=pyhd8ed1ab_1
  - statsmodels=0.14.5=py39h9e4d2f2_0
  - sympy=1.14.0=py39haa95532_0
  - tbb=2021.8.0=h59b6b97_0
  - threadpoolctl=3.6.0=pyhecae5ae_0
  - tk=8.6.15=hf199647_0
  - toml=0.10.2=pyhd8ed1ab_1
  - torchmetrics=1.8.2=pyhd8ed1ab_0
  - tornado=6.5.2=py39h0802e32_0
  - tqdm=4.67.1=pyhd8ed1ab_1
  - traitlets=5.14.3=pyhd8ed1ab_1
  - typing=3.10.0.0=py39haa95532_0
  - typing-extensions=4.15.0=py39haa95532_0
  - typing-inspection=0.4.2=py39haa95532_0
  - typing_extensions=4.15.0=py39haa95532_0
  - tzdata=2025b=h04d1e81_0
  - ucrt=10.0.22621.0=haa95532_0
  - unicodedata2=16.0.0=py39ha55e580_0
  - urllib3=2.5.0=py39haa95532_0
  - vc=14.3=h2df5915_10
  - vc14_runtime=14.44.35208=h4927774_10
  - vs2015_runtime=14.44.35208=ha6b5a95_10
  - wandb=0.21.1=py39had3977d_0
  - wcwidth=0.2.13=pyhd8ed1ab_1
  - wheel=0.45.1=py39haa95532_0
  - win_inet_pton=1.1.0=py39haa95532_1
  - xz=5.6.4=h4754444_1
  - yaml=0.2.5=he774522_0
  - zeromq=4.3.5=h5bddc39_9
  - zipp=3.23.0=pyhd8ed1ab_0
  - zlib=1.3.1=h02ab6af_0
  - zstd=1.5.7=h56299aa_0
  - pip:
      - opencv-python==4.12.0.88
      - torchaudio==2.5.1
      - torchvision==0.20.1
prefix: C:\Users\david\anaconda3\envs\pytorch-brats
